### ISSUE TITLE
Fix seg fault in MLP call (valgrind Py_DECREF bug)

### ISSUE THREAD

**Issue by yrmo** [yrmo/value#15]
```py
import random

from micrograd.engine import Value
from micrograd.nn import Neuron

random.seed(1337)
model = Neuron(1)
model([Value(1.0)])
```

```
$ ../cpython/python --version
Python 3.14.0a0
$ valgrind ../cpython/python demo.py 
==30413== Memcheck, a memory error detector
==30413== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==30413== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==30413== Command: ../cpython/python demo.py
==30413== 
a
b
c
d
e
==30413== Invalid read of size 8
==30413==    at 0x581A5C6: free_binary_closure (engine.c:90)
==30413==    by 0x581A6CF: Value_dealloc (engine.c:219)
==30413==    by 0x2B44D1: _Py_Dealloc (object.c:2851)
==30413==    by 0x3DD99D: Py_DECREF (object.h:932)
==30413==    by 0x3DD99D: _PyEval_EvalFrameDefault (generated_cases.c.h:5013)
==30413==    by 0x3E434A: _PyEval_EvalFrame (pycore_ceval.h:119)
==30413==    by 0x3E434A: _PyEval_Vector (ceval.c:1819)
==30413==    by 0x3E4408: PyEval_EvalCode (ceval.c:599)
==30413==    by 0x4674C3: run_eval_code_obj (pythonrun.c:1292)
==30413==    by 0x468D8C: run_mod (pythonrun.c:1377)
==30413==    by 0x469471: pyrun_file (pythonrun.c:1210)
==30413==    by 0x46A68E: _PyRun_SimpleFileObject (pythonrun.c:459)
==30413==    by 0x46A961: _PyRun_AnyFileObject (pythonrun.c:77)
==30413==    by 0x496765: pymain_run_file_obj (main.c:357)
==30413==  Address 0x4ea3d10 is 0 bytes after a block of size 16 alloc'd
==30413==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==30413==    by 0x581A4F5: unary_closure (engine.c:81)
==30413==    by 0x581A57F: Value_relu (engine.c:194)
==30413==    by 0x24D3F3: method_vectorcall_NOARGS (descrobject.c:447)
==30413==    by 0x239FD2: _PyObject_VectorcallTstate (pycore_call.h:168)
==30413==    by 0x23A0F1: PyObject_Vectorcall (call.c:327)
==30413==    by 0x3CBAB1: _PyEval_EvalFrameDefault (generated_cases.c.h:813)
==30413==    by 0x3E434A: _PyEval_EvalFrame (pycore_ceval.h:119)
==30413==    by 0x3E434A: _PyEval_Vector (ceval.c:1819)
==30413==    by 0x239A52: _PyFunction_Vectorcall (call.c:413)
==30413==    by 0x23C04F: _PyObject_VectorcallDictTstate (call.c:135)
==30413==    by 0x23C2B4: _PyObject_Call_Prepend (call.c:504)
==30413==    by 0x302571: slot_tp_call (typeobject.c:9513)
==30413== 
==30413== Invalid read of size 8
==30413==    at 0x581A5CA: Py_DECREF (object.h:923)
==30413==    by 0x581A5CA: free_binary_closure (engine.c:90)
==30413==    by 0x581A6CF: Value_dealloc (engine.c:219)
==30413==    by 0x2B44D1: _Py_Dealloc (object.c:2851)
==30413==    by 0x3DD99D: Py_DECREF (object.h:932)
==30413==    by 0x3DD99D: _PyEval_EvalFrameDefault (generated_cases.c.h:5013)
==30413==    by 0x3E434A: _PyEval_EvalFrame (pycore_ceval.h:119)
==30413==    by 0x3E434A: _PyEval_Vector (ceval.c:1819)
==30413==    by 0x3E4408: PyEval_EvalCode (ceval.c:599)
==30413==    by 0x4674C3: run_eval_code_obj (pythonrun.c:1292)
==30413==    by 0x468D8C: run_mod (pythonrun.c:1377)
==30413==    by 0x469471: pyrun_file (pythonrun.c:1210)
==30413==    by 0x46A68E: _PyRun_SimpleFileObject (pythonrun.c:459)
==30413==    by 0x46A961: _PyRun_AnyFileObject (pythonrun.c:77)
==30413==    by 0x496765: pymain_run_file_obj (main.c:357)
==30413==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==30413== 
==30413== 
==30413== Process terminating with default action of signal 11 (SIGSEGV)
==30413==  Access not within mapped region at address 0x0
==30413==    at 0x581A5CA: Py_DECREF (object.h:923)
==30413==    by 0x581A5CA: free_binary_closure (engine.c:90)
==30413==    by 0x581A6CF: Value_dealloc (engine.c:219)
==30413==    by 0x2B44D1: _Py_Dealloc (object.c:2851)
==30413==    by 0x3DD99D: Py_DECREF (object.h:932)
==30413==    by 0x3DD99D: _PyEval_EvalFrameDefault (generated_cases.c.h:5013)
==30413==    by 0x3E434A: _PyEval_EvalFrame (pycore_ceval.h:119)
==30413==    by 0x3E434A: _PyEval_Vector (ceval.c:1819)
==30413==    by 0x3E4408: PyEval_EvalCode (ceval.c:599)
==30413==    by 0x4674C3: run_eval_code_obj (pythonrun.c:1292)
==30413==    by 0x468D8C: run_mod (pythonrun.c:1377)
==30413==    by 0x469471: pyrun_file (pythonrun.c:1210)
==30413==    by 0x46A68E: _PyRun_SimpleFileObject (pythonrun.c:459)
==30413==    by 0x46A961: _PyRun_AnyFileObject (pythonrun.c:77)
==30413==    by 0x496765: pymain_run_file_obj (main.c:357)
==30413==  If you believe this happened as a result of a stack
==30413==  overflow in your program's main thread (unlikely but
==30413==  possible), you can try to increase the size of the
==30413==  main thread stack using the --main-stacksize= flag.
==30413==  The main thread stack size used in this run was 8388608.
==30413== 
==30413== HEAP SUMMARY:
==30413==     in use at exit: 1,186,428 bytes in 1,398 blocks
==30413==   total heap usage: 2,530 allocs, 1,132 frees, 3,092,063 bytes allocated
==30413== 
==30413== LEAK SUMMARY:
==30413==    definitely lost: 0 bytes in 0 blocks
==30413==    indirectly lost: 0 bytes in 0 blocks
==30413==      possibly lost: 1,173,046 bytes in 1,349 blocks
==30413==    still reachable: 13,382 bytes in 49 blocks
==30413==         suppressed: 0 bytes in 0 blocks
==30413== Rerun with --leak-check=full to see details of leaked memory
==30413== 
==30413== For lists of detected and suppressed errors, rerun with: -s
==30413== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)
```

**Comment by yrmo** [comment]
Above works something wrong with 3.14, broken 3.11 macos:
```py
from micrograd.engine import Value
from micrograd.nn import Neuron, Layer, MLP

N = 2
model = MLP(N, [N, 1])
print(model([Value(i) for i in range(N)]).data)
```

**Comment by yrmo** [comment]
```py
from micrograd.engine import Value
from micrograd.nn import Neuron, Layer, MLP

N = 2
print("-" * 9, Neuron(N)([Value(i) for i in range(N)]).data)
print("-" * 9, [x.data for x in Layer(N, N)([Value(i) for i in range(N)])])
print("-" * 9, MLP(N, [N, 1])([Value(i) for i in range(N)]).data)
```
```
$ valgrind python demo.py 
==32081== Memcheck, a memory error detector
==32081== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==32081== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==32081== Command: python demo.py
==32081== 
a
b
c
d
e
--------- 0.0
8
a
b
c
a
b
c
9
d
e
d
e
10
--------- [0.0, 0.0]
1
2
8
a
b
c
a
b
c
8
a
b
c
3
4
9
d
e
d
e
10
4
9
d
e
10
5
==32081== Invalid read of size 8
==32081==    at 0x4865162: free_binary_closure (engine.c:90)
==32081==    by 0x4865207: Value_dealloc (engine.c:219)
==32081==    by 0x290F5E: ??? (in /usr/bin/python3.10)
==32081==    by 0x4865244: _Py_DECREF (object.h:500)
==32081==    by 0x4865244: _Py_XDECREF (object.h:567)
==32081==    by 0x4865244: Value_dealloc (engine.c:222)
==32081==    by 0x290F5E: ??? (in /usr/bin/python3.10)
==32081==    by 0x4865244: _Py_DECREF (object.h:500)
==32081==    by 0x4865244: _Py_XDECREF (object.h:567)
==32081==    by 0x4865244: Value_dealloc (engine.c:222)
==32081==    by 0x290F5E: ??? (in /usr/bin/python3.10)
==32081==    by 0x4865244: _Py_DECREF (object.h:500)
==32081==    by 0x4865244: _Py_XDECREF (object.h:567)
==32081==    by 0x4865244: Value_dealloc (engine.c:222)
==32081==    by 0x2523D9: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==32081==    by 0x2479C5: ??? (in /usr/bin/python3.10)
==32081==    by 0x33D255: PyEval_EvalCode (in /usr/bin/python3.10)
==32081==    by 0x368107: ??? (in /usr/bin/python3.10)
==32081==  Address 0x4f670a0 is 0 bytes after a block of size 16 alloc'd
==32081==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==32081==    by 0x48650C9: unary_closure (engine.c:81)
==32081==    by 0x4865137: Value_relu (engine.c:194)
==32081==    by 0x2666C6: ??? (in /usr/bin/python3.10)
==32081==    by 0x24B45B: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==32081==    by 0x257C13: _PyObject_FastCallDictTstate (in /usr/bin/python3.10)
==32081==    by 0x26D86B: _PyObject_Call_Prepend (in /usr/bin/python3.10)
==32081==    by 0x3886FF: ??? (in /usr/bin/python3.10)
==32081==    by 0x258A7A: _PyObject_MakeTpCall (in /usr/bin/python3.10)
==32081==    by 0x251095: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==32081==    by 0x2629FB: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==32081==    by 0x24B26C: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==32081== 
==32081== Invalid read of size 8
==32081==    at 0x4865166: _Py_DECREF (object.h:492)
==32081==    by 0x4865166: free_binary_closure (engine.c:90)
==32081==    by 0x4865207: Value_dealloc (engine.c:219)
==32081==    by 0x290F5E: ??? (in /usr/bin/python3.10)
==32081==    by 0x4865244: _Py_DECREF (object.h:500)
==32081==    by 0x4865244: _Py_XDECREF (object.h:567)
==32081==    by 0x4865244: Value_dealloc (engine.c:222)
==32081==    by 0x290F5E: ??? (in /usr/bin/python3.10)
==32081==    by 0x4865244: _Py_DECREF (object.h:500)
==32081==    by 0x4865244: _Py_XDECREF (object.h:567)
==32081==    by 0x4865244: Value_dealloc (engine.c:222)
==32081==    by 0x290F5E: ??? (in /usr/bin/python3.10)
==32081==    by 0x4865244: _Py_DECREF (object.h:500)
==32081==    by 0x4865244: _Py_XDECREF (object.h:567)
==32081==    by 0x4865244: Value_dealloc (engine.c:222)
==32081==    by 0x2523D9: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==32081==    by 0x2479C5: ??? (in /usr/bin/python3.10)
==32081==    by 0x33D255: PyEval_EvalCode (in /usr/bin/python3.10)
==32081==    by 0x368107: ??? (in /usr/bin/python3.10)
==32081==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==32081== 
==32081== 
==32081== Process terminating with default action of signal 11 (SIGSEGV)
==32081==  Access not within mapped region at address 0x0
==32081==    at 0x4865166: _Py_DECREF (object.h:492)
==32081==    by 0x4865166: free_binary_closure (engine.c:90)
==32081==    by 0x4865207: Value_dealloc (engine.c:219)
==32081==    by 0x290F5E: ??? (in /usr/bin/python3.10)
==32081==    by 0x4865244: _Py_DECREF (object.h:500)
==32081==    by 0x4865244: _Py_XDECREF (object.h:567)
==32081==    by 0x4865244: Value_dealloc (engine.c:222)
==32081==    by 0x290F5E: ??? (in /usr/bin/python3.10)
==32081==    by 0x4865244: _Py_DECREF (object.h:500)
==32081==    by 0x4865244: _Py_XDECREF (object.h:567)
==32081==    by 0x4865244: Value_dealloc (engine.c:222)
==32081==    by 0x290F5E: ??? (in /usr/bin/python3.10)
==32081==    by 0x4865244: _Py_DECREF (object.h:500)
==32081==    by 0x4865244: _Py_XDECREF (object.h:567)
==32081==    by 0x4865244: Value_dealloc (engine.c:222)
==32081==    by 0x2523D9: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==32081==    by 0x2479C5: ??? (in /usr/bin/python3.10)
==32081==    by 0x33D255: PyEval_EvalCode (in /usr/bin/python3.10)
==32081==    by 0x368107: ??? (in /usr/bin/python3.10)
==32081==  If you believe this happened as a result of a stack
==32081==  overflow in your program's main thread (unlikely but
==32081==  possible), you can try to increase the size of the
==32081==  main thread stack using the --main-stacksize= flag.
==32081==  The main thread stack size used in this run was 8388608.
==32081== 
==32081== HEAP SUMMARY:
==32081==     in use at exit: 1,274,052 bytes in 578 blocks
==32081==   total heap usage: 1,957 allocs, 1,379 frees, 3,608,721 bytes allocated
==32081== 
==32081== LEAK SUMMARY:
==32081==    definitely lost: 0 bytes in 0 blocks
==32081==    indirectly lost: 0 bytes in 0 blocks
==32081==      possibly lost: 9,112 bytes in 13 blocks
==32081==    still reachable: 1,264,940 bytes in 565 blocks
==32081==         suppressed: 0 bytes in 0 blocks
==32081== Rerun with --leak-check=full to see details of leaked memory
==32081== 
==32081== For lists of detected and suppressed errors, rerun with: -s
==32081== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)
```

**Comment by yrmo** [comment]
It's relu only happens MLP cause nonlin is only True then

**Comment by yrmo** [comment]
```
ryan@Lambda-TensorBook:~/micrograd$ rr record -n python demo2.py
rr: Saving execution to trace directory `/home/ryan/.local/share/rr/python-0'.
(100, 2) (100,)
MLP of [Layer of [ReLUNeuron(2), ReLUNeuron(2), ReLUNeuron(2), ReLUNeuron(2), ReLUNeuron(2), ReLUNeuron(2), ReLUNeuron(2), ReLUNeuron(2), ReLUNeuron(2), ReLUNeuron(2), ReLUNeuron(2), ReLUNeuron(2), ReLUNeuron(2), ReLUNeuron(2), ReLUNeuron(2), ReLUNeuron(2)], Layer of [ReLUNeuron(16), ReLUNeuron(16), ReLUNeuron(16), ReLUNeuron(16), ReLUNeuron(16), ReLUNeuron(16), ReLUNeuron(16), ReLUNeuron(16), ReLUNeuron(16), ReLUNeuron(16), ReLUNeuron(16), ReLUNeuron(16), ReLUNeuron(16), ReLUNeuron(16), ReLUNeuron(16), ReLUNeuron(16)], Layer of [LinearNeuron(16)]]
number of parameters 337
<engine.Value object at 0x7882e2d63cb0> 0.5
Segmentation fault
ryan@Lambda-TensorBook:~/micrograd$ rr replay
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/python3.10...
(No debugging symbols found in /usr/bin/python3.10)
Really redefine built-in command "restart"? (y or n) [answered Y; input not from terminal]
Really redefine built-in command "jump"? (y or n) [answered Y; input not from terminal]
Remote debugging using 127.0.0.1:43913
Reading symbols from /lib64/ld-linux-x86-64.so.2...
Reading symbols from /usr/lib/debug/.build-id/24/6ac0d8deba5a40c63e9a1a87d4d779d8eb589f.debug...
BFD: warning: system-supplied DSO at 0x6fffd000 has a section extending past end of file
0x00007882f2cec290 in _start () from /lib64/ld-linux-x86-64.so.2
(rr) bt
#0  0x00007882f2cec290 in _start () from /lib64/ld-linux-x86-64.so.2
#1  0x0000000000000002 in ?? ()
#2  0x00007ffd40c192d5 in ?? ()
#3  0x00007ffd40c192dc in ?? ()
#4  0x0000000000000000 in ?? ()
(rr) 
#0  0x00007882f2cec290 in _start () from /lib64/ld-linux-x86-64.so.2
#1  0x0000000000000002 in ?? ()
#2  0x00007ffd40c192d5 in ?? ()
#3  0x00007ffd40c192dc in ?? ()
#4  0x0000000000000000 in ?? ()
(rr) 
#0  0x00007882f2cec290 in _start () from /lib64/ld-linux-x86-64.so.2
#1  0x0000000000000002 in ?? ()
#2  0x00007ffd40c192d5 in ?? ()
#3  0x00007ffd40c192dc in ?? ()
#4  0x0000000000000000 in ?? ()
(rr) c
Continuing.
(100, 2) (100,)
MLP of [Layer of [ReLUNeuron(2), ReLUNeuron(2), ReLUNeuron(2), ReLUNeuron(2), ReLUNeuron(2), ReLUNeuron(2), ReLUNeuron(2), ReLUNeuron(2), ReLUNeuron(2), ReLUNeuron(2), ReLUNeuron(2), ReLUNeuron(2), ReLUNeuron(2), ReLUNeuron(2), ReLUNeuron(2), ReLUNeuron(2)], Layer of [ReLUNeuron(16), ReLUNeuron(16), ReLUNeuron(16), ReLUNeuron(16), ReLUNeuron(16), ReLUNeuron(16), ReLUNeuron(16), ReLUNeuron(16), ReLUNeuron(16), ReLUNeuron(16), ReLUNeuron(16), ReLUNeuron(16), ReLUNeuron(16), ReLUNeuron(16), ReLUNeuron(16), ReLUNeuron(16)], Layer of [LinearNeuron(16)]]
number of parameters 337
<engine.Value object at 0x7882e2d63cb0> 0.5

Program received signal SIGSEGV, Segmentation fault.
0x00007882ee64666a in backward_relu (self=0x7882e1b5a3f0, out=0x0) at engine.c:68
warning: Source file is more recent than executable.
68	    self->grad += ((self->data > 0) ? 1.0 : 0) * out->grad;
(rr) p self
$1 = (ValueObject *) 0x7882e1b5a3f0
(rr) p *self
$2 = {ob_base = {ob_refcnt = 4, ob_type = 0x7882ee64a460 <ValueType>}, data = -0.045237261571086027, grad = 0, _backward = 0x61731bc420a0, 
  _prev = 0x7882e1b61fc0, _op = 0x7882f205a9e0 "+"}
(rr) p out
$3 = (ValueObject *) 0x0
(rr) p *out
Cannot access memory at address 0x0
(rr) p out->grad
Cannot access memory at address 0x18
(rr) p self->data
$4 = -0.045237261571086027
(rr) 
```
e67c9cc75d963161d453682cbb0d750c67dc0439
